commands_restrictions:
  queue:
    conditions:
      - sender=@devprod
queue_rules:
  - name: dev
    speculative_checks: 3
    batch_size: 4
    draft_bot_account: vbotbuildovich
    conditions:
      - base=dev