queue_rules:
  - name: default
    allow_inplace_checks: true
    draft_bot_account: vbotbuildovich
    conditions:
      - check-success=render
      - check-success=Lint go files
      - check-success=Lint python files
      - check-success=Lint shell scripts
      - check-success=Run tests (linux, amd64)
pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=render
      - check-success=Lint go files
      - check-success=Lint python files
      - check-success=Lint shell scripts
    actions:
      label:
        add:
          - queued
      queue:
        name: default
        method: rebase
        update_method: rebase
