queue_rules:
  - name: default
    speculative_checks: 3
    batch_size: 4
    draft_bot_account: vbotbuildovich
    conditions:
      - check-success=Lint go files
      - check-success=Lint python files
      - check-success=Lint shell scripts
      - check-success=Run tests (linux, amd64)