pull_request_rules:
  - name: enqueue on label
    conditions:
      - base=dev
      - label=merge-queue
    actions:
      queue:
        name: dev
        method: rebase
queue_rules:
  - name: dev
    speculative_checks: 3
    batch_size: 4
    draft_bot_account: vbotbuildovich
    conditions:
      - base=dev
      - label=merge-queue