# Copyright 2020 Vectorized, Inc.
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.md
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0

name: build-test
on: [push, pull_request]

jobs:
  build:
    name: build redpanda
    runs-on: ubuntu-20.04

    steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: prepare toolchain container
          run: |
            docker pull docker.io/vectorized/redpanda-toolchain || true
            chmod 0775 install-dependencies.sh
            cp tools/docker/Dockerfile.ignore .dockerignore
            docker build \
              --cache-from docker.io/vectorized/redpanda-toolchain \
              --tag rp-toolchain \
              --file tools/docker/Dockerfile \
              .
            rm .dockerignore

        - name: ccache cache files
          uses: actions/cache@v2
          with:
            path: /dev/shm/redpanda
            key: ccache-${{github.ref}}
            restore-keys: ccache

        - name: build & test
          run: |
            export CCACHE_COMPRESS=true
            export CCACHE_COMPRESSLEVEL=6
            export CCACHE_MAXSIZE=200M

            ccache -p # print the config
            ccache -s # print the stats before reusing
            ccache -z # zero the stats

            docker run --rm \
              --privileged \
              --ipc=host \
              -v $PWD:$PWD \
              -w $PWD \
              rp-toolchain \
              ./build.sh

            ccache -s # print the stats after the build
